theme: jekyll-theme-cayman

firmware-update-raw: https://raw.githubusercontent.com/A2L5E0X1/samsung_fwupdate/master/current.
firmware-update-releases: https://api.github.com/repos/A2L5E0X1/samsung_fwupdate/releases/tags/
firmware-update-download: https://github.com/A2L5E0X1/samsung_fwupdate/releases/download/
lineage_ota_base_url: https://raw.githubusercontent.com/A2L5E0X1/lineage/master/
